name: Plugin update

on:
  workflow_dispatch:
    inputs:
      repo_owner:
        type: string
        description: Username of the target repository's owner
        required: true
      repo_name:
        type: string
        description: Name of the target repository
        required: true
      repo_id:
        type: string
        description: Id of the target repository
        required: true

jobs:
  build:
    name: Build plugins
    runs-on: ubuntu-20.04
    timeout-minutes: 4
    steps:
      - name: Checkout target plugin repository
        uses: actions/checkout@v3
        with:
          repository: "${{ github.event.inputs.repo_owner }}/${{ github.event.inputs.repo_name }}"

      - name: Setup PNPM
        uses: pnpm/action-setup@v2

      # aliuhook
      # - name: Setup JDK 11
      #   uses: actions/setup-java@v2
      #   with:
      #     java-version: 11
      #     distribution: zulu

      # - name: Setup Android SDK
      #   uses: android-actions/setup-android@7c5672355aaa8fde5f97a91aa9a99616d1ace6bc

      - name: Build Plugin
        id: build
        env:
          CI: "true"
        run: |
          echo "dist_folder=$(jq -r '.distFolder' < .aliucordrc)" >> $GITHUB_OUTPUT
          jq -r '.buildAllCommand' < .aliucordrc | sh

      - name: Upload plugins
        uses: actions/upload-artifact@v3
        with:
          name: INSECURE-DO-NOT-USE
          path: ${{ steps.build.outputs.dist_folder }}/*.{zip,json} .aliucordrc

  make_pr:
    name: Make/Update PR
    runs-on: ubuntu-20.04
    timeout-minutes: 1
    steps:
      - name: Checkout plugin repo
        uses: actions/checkout@v3
        with:
          repository: Aliucord/plugins
          path: plugins
          ref: data

      - name: Download plugins
        uses: actions/download-artifact@v3
        with:
          name: INSECURE-DO-NOT-USE
          path: build.zip

      - name: Extract plugins
        run: |
          unzip build.zip -d build
          cd build
          rm `jq -r '.ignoredPlugins | map("'\''\(.)'.zip\''") | join(" ")' < .aliucordrc`
          rm .aliucordrc

      - name: Test for existing PR
        id: test_existing
        run: |
          branch_name="update/${{ github.event.inputs.repo_id }}"
          if git ls-remote --exit-code faraway; then
            echo "base_branch=$branch_name" >> $GITHUB_OUTPUT
          else
            echo "base_branch=data"  >> $GITHUB_OUTPUT
          fi

      - name: Download target plugin repository
        uses: actions/checkout@v3
        with:
          repository: "${{ github.event.inputs.repo_owner }}/${{ github.event.inputs.repo_name }}"
          path: plugins/repositories/${{ github.event.inputs.repo_id }}
          ref: ${{ steps.test_existing.outputs.base_branch }}

      - name: Update plugins in repo
        run: |
          cd plugins/modern
          
          # Make new branch
          if [ "${{ steps.test_existing.outputs.base_branch }}" != "data" ]; then
            git checkout -b ${{ steps.test_existing.outputs.base_branch }}
          fi
          src_commit=`cd plugins/repositories/${{ github.event.inputs.repo_id }} && git rev-parse HEAD`

          # Copy plugin stuff into plugin dir
          for pluginPath in $GITHUB_WORKSPACE/build/*.zip; do
            pluginName=`basename ${plugin::-4}`
            mkdir -p $pluginName

            # .owner validation
            ownerFile=./$pluginName/.owner
            if [ -f $ownerFile ]  && [ "$(<$ownerFile)" != "${{ github.event.inputs.repo_id }}" ]; then echo "Failed validation! This repository does not own the plugin $pluginName"; exit 1; fi
            echo ${{ github.event.inputs.repo_id }} > $ownerFile

            # .zip
            mv $pluginPath ./$pluginName

            # manifest.json
            mv -T `dirname $pluginPath`/$pluginName-manifest.json ./$pluginName/manifest.json

            # metadata.json
            hash=`echo -n $pluginPath | sha256sum`
            cat ./$pluginName/manifest.json | jq -c --arg hash $hash --arg commit $src_commit '{hash: $hash, changelog: .changelog, commit: $commit, version: .version}' > ./$pluginName/metadata.json

            # symlink
            ln -s ../repositories/${{ github.event.inputs.repo_id }} ./$pluginName/repository
          done

          # updater.json
          cat updater.json **/manifest.json | jq -cs '.[0] + (.[1:] | reduce .[] as $manifest ({}; . + {($manifest.name): {version: $manifest.version}}))' > updater.json

          # full.json
          cat **/manifest.json | jq -cs 'if group_by(.name) | any(length>1) then "Duplicate manifest name key\n" | halt_error(1) else . end' > full.json

          # Remove .git from copied repo
          rm -rf plugins/repositories/${{ github.event.inputs.repo_id }}/.git

          # Commit
          cd $GITHUB_WORKSPACE/plugins
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add *
          git commit -m "build: commit ${{ github.event.inputs.repo_owner }}/${{ github.event.inputs.repo_name }}@$src_commit" || exit 0
          git push -u origin ${{ steps.test_existing.outputs.base_branch }}

# TODO: make pr
